/**
 * Cron Jobs - Automated notifications and tasks
 * 
 * Schedule:
 * - 08:00 AM: Birthday wishes, timetable reminders
 * - Every minute: Process scheduled notifications
 */
const cron = require('node-cron');
const Notification = require('../models/Notification');
const NotificationRead = require('../models/NotificationRead');
const Student = require('../models/Student');
const Faculty = require('../models/Faculty');
const Timetable = require('../models/Timetable');
const DeviceToken = require('../models/DeviceToken');
const { sendPushNotification } = require('../config/firebase');
const { DAYS } = require('../utils/constants');
const logger = require('../utils/logger');

/**
 * Initialize all cron jobs
 */
const initCronJobs = () => {
    // 08:00 AM daily - Birthday wishes
    cron.schedule('0 8 * * *', async () => {
        logger.info('Running birthday wishes job...');
        await generateBirthdayWishes();
    }, { timezone: 'Asia/Kolkata' });

    // 08:00 AM daily - Timetable reminders
    cron.schedule('0 8 * * 1-6', async () => {
        logger.info('Running timetable reminder job...');
        await generateTimetableReminders();
    }, { timezone: 'Asia/Kolkata' });

    // Every minute - Process scheduled notifications
    cron.schedule('* * * * *', async () => {
        await processScheduledNotifications();
    }, { timezone: 'Asia/Kolkata' });

    // Every day at midnight - Clean expired notifications
    cron.schedule('0 0 * * *', async () => {
        logger.info('Running notification cleanup job...');
        await cleanExpiredNotifications();
    }, { timezone: 'Asia/Kolkata' });

    logger.info('All cron jobs scheduled successfully');
};

/**
 * Generate birthday wish notifications
 */
const generateBirthdayWishes = async () => {
    try {
        const today = new Date();
        const month = today.getMonth() + 1;
        const day = today.getDate();

        // Find students with birthday today
        const birthdayStudents = await Student.find({
            $expr: {
                $and: [
                    { $eq: [{ $month: '$dob' }, month] },
                    { $eq: [{ $dayOfMonth: '$dob' }, day] },
                ]
            }
        }).select('name').lean();

        if (birthdayStudents.length === 0) {
            logger.info('No birthdays today');
            return;
        }

        // Create birthday notification
        const names = birthdayStudents.map(s => s.name).join(', ');
        const title = '🎂 Birthday Wishes!';
        const message = birthdayStudents.length === 1
            ? `Happy Birthday to ${names}! 🎉 Wishing you a wonderful day!`
            : `Happy Birthday to ${names}! 🎉 Wishing them all a wonderful day!`;

        await Notification.create({
            title,
            message,
            category: 'Birthday',
            priority: 'low',
            targetYears: [],
            targetSections: [],
            isAutoGenerated: true,
            isSent: true,
            createdBy: null, // System generated
        });

        // Send push notification
        const tokens = await DeviceToken.find({ isActive: true }).select('token').lean();
        const tokenStrings = tokens.map(t => t.token).filter(Boolean);
        if (tokenStrings.length > 0) {
            await sendPushNotification(tokenStrings, title, message, { category: 'Birthday' });
        }

        logger.info(`Birthday notification sent for ${birthdayStudents.length} student(s)`);
    } catch (error) {
        logger.error('Birthday wishes job error:', error);
    }
};

/**
 * Generate timetable reminder notifications
 */
const generateTimetableReminders = async () => {
    try {
        const today = new Date();
        const dayIndex = today.getDay(); // 0=Sun, 1=Mon...
        if (dayIndex === 0) return; // Skip Sunday

        const dayName = DAYS[dayIndex - 1];

        // Get unique academicYear ObjectIds with classes today
        const timetableEntries = await Timetable.find({ day: dayName })
            .distinct('academicYear');

        if (timetableEntries.length === 0) {
            logger.info('No timetable entries for today');
            return;
        }

        const title = '📚 Today\'s Timetable Reminder';
        const message = `Good morning! Check your timetable for today (${dayName}). Have a productive day!`;

        const notification = await Notification.create({
            title,
            message,
            category: 'Timetable',
            priority: 'low',
            targetYears: [],
            targetSections: [],
            isAutoGenerated: true,
            isSent: true,
            expiryDate: new Date(today.getTime() + 24 * 60 * 60 * 1000), // Expires in 24 hours
            createdBy: null,
        });

        // Send push notification
        const tokens = await DeviceToken.find({ isActive: true }).select('token').lean();
        const tokenStrings = tokens.map(t => t.token).filter(Boolean);
        if (tokenStrings.length > 0) {
            await sendPushNotification(tokenStrings, title, message, {
                notificationId: notification._id.toString(),
                category: 'Timetable',
            });
        }

        logger.info('Timetable reminder sent');
    } catch (error) {
        logger.error('Timetable reminder job error:', error);
    }
};

/**
 * Process scheduled notifications that are due.
 *
 * CRITICAL FIX (Race Condition / Duplicate Send Prevention):
 * Each notification is claimed atomically using findOneAndUpdate with
 * { isSent: false } as the query and { $set: { isSent: true } } as the update.
 * Only the server instance that successfully claims the document (gets a non-null
 * return) will send the push notification. This prevents duplicate sends when
 * multiple server instances are running.
 */
const processScheduledNotifications = async () => {
    try {
        const now = new Date();

        // Find all due-but-unsent scheduled notifications (IDs only)
        const dueNotifications = await Notification.find({
            isScheduled: true,
            isSent: false,
            scheduleTime: { $lte: now },
        }).select('_id').lean();

        for (const { _id } of dueNotifications) {
            // Atomically claim this notification: only one server instance wins
            const claimed = await Notification.findOneAndUpdate(
                { _id, isScheduled: true, isSent: false }, // Guard: must still be unsent
                { $set: { isSent: true } },
                { new: true }
            );

            if (!claimed) {
                // Another instance already claimed it — skip
                continue;
            }

            // Send push notification — respect targeting
            let tokenStrings = [];
            if (claimed.targetYears && claimed.targetYears.length > 0) {
                const studentQuery = { academicYear: { $in: claimed.targetYears } };
                if (claimed.targetSections && claimed.targetSections.length > 0) {
                    studentQuery.section = { $in: claimed.targetSections };
                }
                const [students, staffTokens] = await Promise.all([
                    Student.find(studentQuery).select('userId').lean(),
                    DeviceToken.find({ role: { $in: ['faculty', 'admin'] }, isActive: true }).select('token').lean(),
                ]);
                const studentUserIds = students.map(s => s.userId.toString());
                const [studentTokens] = await Promise.all([
                    DeviceToken.find({ userId: { $in: studentUserIds }, isActive: true }).select('token').lean(),
                ]);
                const seen = new Set();
                tokenStrings = [...studentTokens, ...staffTokens]
                    .map(t => t.token)
                    .filter(t => t && !seen.has(t) && seen.add(t));
            } else {
                const tokens = await DeviceToken.find({ isActive: true }).select('token').lean();
                tokenStrings = tokens.map(t => t.token).filter(Boolean);
            }

            if (tokenStrings.length > 0) {
                await sendPushNotification(
                    tokenStrings,
                    claimed.title,
                    claimed.message ? claimed.message.substring(0, 200) : '',
                    { notificationId: claimed._id.toString(), category: claimed.category || '' }
                );
            }

            logger.info(`Scheduled notification sent: ${claimed.title}`);
        }
    } catch (error) {
        logger.error('Process scheduled notifications error:', error);
    }
};

/**
 * Clean expired auto-generated notifications.
 * Also deletes associated NotificationRead records to prevent orphans.
 */
const cleanExpiredNotifications = async () => {
    try {
        // Find expired auto-generated notification IDs first
        const expiredDocs = await Notification.find({
            expiryDate: { $lt: new Date() },
            isAutoGenerated: true,
        }).select('_id').lean();

        if (expiredDocs.length === 0) return;

        const expiredIds = expiredDocs.map(d => d._id);

        // Delete orphan read records first, then delete the notifications
        const [readResult, notifResult] = await Promise.all([
            NotificationRead.deleteMany({ notificationId: { $in: expiredIds } }),
            Notification.deleteMany({ _id: { $in: expiredIds } }),
        ]);

        logger.info(`Cleaned ${notifResult.deletedCount} expired auto-generated notifications and ${readResult.deletedCount} associated read records`);
    } catch (error) {
        logger.error('Clean expired notifications error:', error);
    }
};

module.exports = { initCronJobs };
