/**
 * Cron Jobs - Automated notifications and tasks
 * 
 * Schedule:
 * - 08:00 AM: Birthday wishes, timetable reminders
 * - Every minute: Process scheduled notifications
 */
const cron = require('node-cron');
const Notification = require('../models/Notification');
const Student = require('../models/Student');
const Faculty = require('../models/Faculty');
const Timetable = require('../models/Timetable');
const DeviceToken = require('../models/DeviceToken');
const { sendPushNotification } = require('../config/firebase');
const { DAYS } = require('../utils/constants');
const logger = require('../utils/logger');

/**
 * Initialize all cron jobs
 */
const initCronJobs = () => {
    // 08:00 AM daily - Birthday wishes
    cron.schedule('0 8 * * *', async () => {
        logger.info('Running birthday wishes job...');
        await generateBirthdayWishes();
    }, { timezone: 'Asia/Kolkata' });

    // 08:00 AM daily - Timetable reminders
    cron.schedule('0 8 * * 1-6', async () => {
        logger.info('Running timetable reminder job...');
        await generateTimetableReminders();
    }, { timezone: 'Asia/Kolkata' });

    // Every minute - Process scheduled notifications
    cron.schedule('* * * * *', async () => {
        await processScheduledNotifications();
    }, { timezone: 'Asia/Kolkata' });

    // Every day at midnight - Clean expired notifications
    cron.schedule('0 0 * * *', async () => {
        logger.info('Running notification cleanup job...');
        await cleanExpiredNotifications();
    }, { timezone: 'Asia/Kolkata' });

    logger.info('All cron jobs scheduled successfully');
};

/**
 * Generate birthday wish notifications
 */
const generateBirthdayWishes = async () => {
    try {
        const today = new Date();
        const month = today.getMonth() + 1;
        const day = today.getDate();

        // Find students with birthday today
        const birthdayStudents = await Student.find({
            $expr: {
                $and: [
                    { $eq: [{ $month: '$dob' }, month] },
                    { $eq: [{ $dayOfMonth: '$dob' }, day] },
                ]
            }
        });

        if (birthdayStudents.length === 0) {
            logger.info('No birthdays today');
            return;
        }

        // Create birthday notification
        const names = birthdayStudents.map(s => s.name).join(', ');
        const title = '🎂 Birthday Wishes!';
        const message = birthdayStudents.length === 1
            ? `Happy Birthday to ${names}! 🎉 Wishing you a wonderful day!`
            : `Happy Birthday to ${names}! 🎉 Wishing them all a wonderful day!`;

        await Notification.create({
            title,
            message,
            category: 'Birthday',
            priority: 'low',
            targetYears: [],
            targetSections: [],
            isAutoGenerated: true,
            isSent: true,
            createdBy: null, // System generated
        });

        // Send push notification
        const tokens = await DeviceToken.find({ isActive: true }).select('token');
        const tokenStrings = tokens.map(t => t.token).filter(Boolean);
        if (tokenStrings.length > 0) {
            await sendPushNotification(tokenStrings, title, message, { category: 'Birthday' });
        }

        logger.info(`Birthday notification sent for ${birthdayStudents.length} student(s)`);
    } catch (error) {
        logger.error('Birthday wishes job error:', error);
    }
};

/**
 * Generate timetable reminder notifications
 */
const generateTimetableReminders = async () => {
    try {
        const today = new Date();
        const dayIndex = today.getDay(); // 0=Sun, 1=Mon...
        if (dayIndex === 0) return; // Skip Sunday

        const dayName = DAYS[dayIndex - 1];

        // Get unique academicYear ObjectIds with classes today
        const timetableEntries = await Timetable.find({ day: dayName })
            .distinct('academicYear');

        if (timetableEntries.length === 0) {
            logger.info('No timetable entries for today');
            return;
        }

        const title = '📚 Today\'s Timetable Reminder';
        const message = `Good morning! Check your timetable for today (${dayName}). Have a productive day!`;

        const notification = await Notification.create({
            title,
            message,
            category: 'Timetable',
            priority: 'low',
            targetYears: [],
            targetSections: [],
            isAutoGenerated: true,
            isSent: true,
            expiryDate: new Date(today.getTime() + 24 * 60 * 60 * 1000), // Expires in 24 hours
            createdBy: null,
        });

        // Send push notification
        const tokens = await DeviceToken.find({ isActive: true }).select('token');
        const tokenStrings = tokens.map(t => t.token).filter(Boolean);
        if (tokenStrings.length > 0) {
            await sendPushNotification(tokenStrings, title, message, {
                notificationId: notification._id.toString(),
                category: 'Timetable',
            });
        }

        logger.info('Timetable reminder sent');
    } catch (error) {
        logger.error('Timetable reminder job error:', error);
    }
};

/**
 * Process scheduled notifications that are due
 */
const processScheduledNotifications = async () => {
    try {
        const now = new Date();
        const scheduledNotifications = await Notification.find({
            isScheduled: true,
            isSent: false,
            scheduleTime: { $lte: now },
        });

        for (const notification of scheduledNotifications) {
            notification.isSent = true;
            await notification.save();

            // Send push notification
            const tokens = await DeviceToken.find({ isActive: true }).select('token');
            const tokenStrings = tokens.map(t => t.token).filter(Boolean);
            if (tokenStrings.length > 0) {
                await sendPushNotification(
                    tokenStrings,
                    notification.title,
                    notification.message.substring(0, 200),
                    { notificationId: notification._id.toString(), category: notification.category }
                );
            }

            logger.info(`Scheduled notification sent: ${notification.title}`);
        }
    } catch (error) {
        logger.error('Process scheduled notifications error:', error);
    }
};

/**
 * Clean expired notifications (soft cleanup - mark as expired)
 */
const cleanExpiredNotifications = async () => {
    try {
        const result = await Notification.deleteMany({
            expiryDate: { $lt: new Date() },
            isAutoGenerated: true, // Only auto-clean system-generated ones
        });

        if (result.deletedCount > 0) {
            logger.info(`Cleaned ${result.deletedCount} expired auto-generated notifications`);
        }
    } catch (error) {
        logger.error('Clean expired notifications error:', error);
    }
};

module.exports = { initCronJobs };
