/**
 * Notification Model - Primary feature
 * 
 * Supports targeted notifications with scheduling, expiry, and read tracking.
 */
const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
    title: {
        type: String,
        required: [true, 'Title is required'],
        trim: true,
        maxlength: [200, 'Title must be under 200 characters'],
    },
    message: {
        type: String,
        required: [true, 'Message is required'],
        trim: true,
        maxlength: [5000, 'Message must be under 5000 characters'],
    },
    category: {
        type: String,
        required: [true, 'Category is required'],
    },
    priority: {
        type: String,
        enum: ['low', 'medium', 'high', 'urgent'],
        default: 'medium',
    },
    targetYears: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'AcademicYear',
    }],
    targetSections: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Section',
    }],
    link: {
        type: String,
        trim: true,
    },
    attachment: {
        type: String, // File path/URL
        trim: true,
    },
    attachmentName: {
        type: String,
        trim: true,
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: function() {
            return !this.isAutoGenerated;
        },
    },
    scheduleTime: {
        type: Date,
    },
    expiryDate: {
        type: Date,
    },
    isScheduled: {
        type: Boolean,
        default: false,
    },
    isSent: {
        type: Boolean,
        default: false,
    },
    isAutoGenerated: {
        type: Boolean,
        default: false,
    },
    readCount: {
        type: Number,
        default: 0,
    },
}, {
    timestamps: true,
});

// Indexes for efficient querying
notificationSchema.index({ createdAt: -1 });
notificationSchema.index({ category: 1 });
notificationSchema.index({ priority: 1 });
notificationSchema.index({ targetYears: 1 });
notificationSchema.index({ targetSections: 1 });
notificationSchema.index({ isScheduled: 1, isSent: 1, scheduleTime: 1 });
notificationSchema.index({ expiryDate: 1 });

// Text index for search
notificationSchema.index({ title: 'text', message: 'text' });

module.exports = mongoose.model('Notification', notificationSchema);
